<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PackageIcon>new_project.png</PackageIcon>
    <ApplicationIcon>table tools icon.ico</ApplicationIcon>
    <AssemblyName>Table Tools</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="ui\stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="table tools icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Users\tyler\OneDrive\Desktop\new_project.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SFML.Audio" Version="2.6.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

</Project>
